# Generated by Django 4.1 on 2022-08-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvt_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familiares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Brothers',
        ),
        migrations.DeleteModel(
            name='Grandparents',
        ),
        migrations.DeleteModel(
            name='Parents',
        ),
    ]
