# Generated by Django 4.1 on 2022-08-30 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvt_app', '0002_familiares_delete_brothers_delete_grandparents_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Familiares',
        ),
    ]
