# Generated by Django 4.1 on 2022-08-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mvt_app', '0003_delete_familiares'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familiares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('profession', models.CharField(max_length=128)),
                ('relationship', models.CharField(max_length=128)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
